version: '2'
services:
    wsgi:
        build: airport
        depends_on:
            - database

        ports:
            - "8000:8000"
            - "8080:8080"

        environment:
            - DJANGO_DEBUG

        volumes:
            - ../../djangoproject:/usr/src

    database:
        image: postgres:9.6

    web:
        image: nginx
        depends_on:
            - wsgi

        ports:
            - "80:80"

        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
